name: test

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - release

jobs:
  test:
    name: run tests using pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry

      - name: Cache pip packages
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: |
            ~/.cache/pip
            ~/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies using poetry
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest -q tests/
